
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "conversion", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Conversion {


    /**
     * 
     * @param code
     * @return
     *     returns service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcompte", targetNamespace = "http://service/", className = "service.Getcompte")
    @ResponseWrapper(localName = "getcompteResponse", targetNamespace = "http://service/", className = "service.GetcompteResponse")
    @Action(input = "http://service/conversion/getcompteRequest", output = "http://service/conversion/getcompteResponse")
    public Compte getcompte(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @param montant
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroEnDh", targetNamespace = "http://service/", className = "service.ConversionEuroEnDh")
    @ResponseWrapper(localName = "conversionEuroEnDhResponse", targetNamespace = "http://service/", className = "service.ConversionEuroEnDhResponse")
    @Action(input = "http://service/conversion/conversionEuroEnDhRequest", output = "http://service/conversion/conversionEuroEnDhResponse")
    public Double conversionEuroEnDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service/", className = "service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service/", className = "service.GetComptesResponse")
    @Action(input = "http://service/conversion/getComptesRequest", output = "http://service/conversion/getComptesResponse")
    public List<Compte> getComptes();

}
